<?php

namespace Database\Seeders;

use App\Models\Site;
use Illuminate\Database\Seeder;

class SiteSeeder extends Seeder
{
    public function run(): void
    {
        foreach ($this->sites() as $site) {
            Site::query()->updateOrCreate(
                ['slug' => $site['slug']],
                $site,
            );
        }
    }

    protected function sites(): array
    {
        return [
            [
                'nombre_empresa' => 'Logistica Pro',
                'slug' => 'logistica-pro',
                'dominio' => 'logistica.test',
                'tema' => 'modern-blue',
                'logo' => null,
                'imagen_principal' => 'https://images.unsplash.com/photo-1553413077-190dd305871c?auto=format&fit=crop&w=1200&q=80',
                'telefono' => '+52 55 1234 5678',
                'email' => 'ventas@logisticapro.mx',
                'direccion' => 'Ciudad de Mexico, Mexico',
                'slogan' => 'Operaciones que se ven bien y funcionan mejor.',
                'titulo_hero' => 'Soluciones logisticas claras, rapidas y confiables.',
                'texto_hero' => 'Una plantilla empresarial que puede cambiar de identidad, mensaje e imagen desde un panel central para adaptarse a cada cliente.',
                'quienes_somos' => 'Somos una empresa enfocada en operaciones, distribucion y atencion comercial. Esta demo muestra como un sitio corporativo puede personalizarse en minutos con logo, imagen principal, datos de contacto y secciones informativas.',
                'caracteristicas' => [
                    ['titulo' => 'Confianza', 'descripcion' => 'Operamos con los mas altos estandares de seguridad y transparencia para tu tranquilidad.', 'icono' => 'M10 1a4.5 4.5 0 00-4.5 4.5V9H5a2 2 0 00-2 2v6a2 2 0 002 2h10a2 2 0 002-2v-6a2 2 0 00-2-2h-.5V5.5A4.5 4.5 0 0010 1zm3 8V5.5a3 3 0 10-6 0V9h6z'],
                    ['titulo' => 'Innovacion', 'descripcion' => 'Mejoramos continuamente nuestros procesos utilizando tecnologia de vanguardia.', 'icono' => 'M15.312 11.424a5.5 5.5 0 01-9.201 2.466l-.312-.311h2.433a.75.75 0 000-1.5H3.989a.75.75 0 00-.75.75v4.242a.75.75 0 001.5 0v-2.43l.31.31a7 7 0 0011.712-3.138.75.75 0 00-1.449-.39zm1.23-3.723a.75.75 0 00.219-.53V2.929a.75.75 0 00-1.5 0V5.36l-.31-.31A7 7 0 003.239 8.188a.75.75 0 101.448.389A5.5 5.5 0 0113.89 6.11l.311.31h-2.432a.75.75 0 000 1.5h4.243a.75.75 0 00.53-.219z'],
                    ['titulo' => 'Calidad', 'descripcion' => 'Entregamos resultados excepcionales garantizando la satisfaccion de nuestros clientes.', 'icono' => 'M10 18a8 8 0 100-16 8 8 0 000 16zm3.857-9.809a.75.75 0 00-1.214-.882l-3.483 4.79-1.88-1.88a.75.75 0 10-1.06 1.061l2.5 2.5a.75.75 0 001.137-.089l4-5.5z'],
                ],
                'servicios' => [
                    ['titulo' => 'Especialidad Uno', 'descripcion' => 'Distribucion y ultima milla para marcas y retailers.', 'icono' => 'M3.75 13.5l10.5-11.25L12 10.5h8.25L9.75 21.75 12 13.5H3.75z'],
                    ['titulo' => 'Especialidad Dos', 'descripcion' => 'Administracion de inventario y trazabilidad operativa.', 'icono' => 'M15.59 14.37a6 6 0 01-5.84 7.38v-4.8m5.84-2.58a14.98 14.98 0 006.16-12.12A14.98 14.98 0 009.631 8.41m5.96 5.96a14.926 14.926 0 01-5.841 2.58m-.119-8.54a6 6 0 00-7.381 5.84h4.8m2.581-5.84a14.927 14.927 0 00-2.58 5.84m2.699 2.7c-.103.021-.207.041-.311.06a15.09 15.09 0 01-2.448-2.45m.31-.31c.019-.104.039-.208.06-.311'],
                    ['titulo' => 'Especialidad Tres', 'descripcion' => 'Atencion comercial y coordinacion de entregas empresariales.', 'icono' => 'M9 12.75L11.25 15 15 9.75M21 12c0 1.268-.63 2.39-1.593 3.068a3.745 3.745 0 01-1.043 3.296 3.745 3.745 0 01-3.296 1.043A3.745 3.745 0 0112 21c-1.268 0-2.39-.63-3.068-1.593a3.746 3.746 0 01-3.296-1.043 3.745 3.745 0 01-1.043-3.296A3.745 3.745 0 013 12c0-1.268.63-2.39 1.593-3.068a3.745 3.745 0 011.043-3.296 a3.746 3.746 0 013.296-1.043A3.746 3.746 0 0112 3c1.268 0 2.39.63 3.068 1.593a3.746 3.746 0 013.296 1.043 3.746 3.746 0 011.043 3.296A3.745 3.745 0 0121 12z'],
                ],
                'orden_secciones' => Site::getDefaultSectionOrderForForm(),
                'cta_config' => array_merge(Site::getDefaultCtaConfig(), [
                    'enabled' => true,
                    'label' => 'Cotiza tu proyecto',
                    'url' => 'https://wa.me/525512345678',
                    'placement' => 'navbar',
                ]),
                'social_links' => array_merge(Site::getDefaultSocialLinks(), [
                    'whatsapp' => 'https://wa.me/525512345678',
                    'facebook' => 'https://facebook.com/logisticapro',
                    'instagram' => 'https://instagram.com/logisticapro',
                    'contact_url' => 'https://wa.me/525512345678',
                ]),
                'seo_config' => Site::getDefaultSeoConfig(),
                'tracking_config' => Site::getDefaultTrackingConfig(),
                'textos_ui' => [
                    'nav_inicio' => 'Inicio',
                    'nav_nosotros' => 'Nosotros',
                    'nav_servicios' => 'Servicios',
                    'nav_contacto' => 'Contacto',
                    'cta_hero' => 'Contactanos ahora',
                    'cta_hero_secundario' => 'Ver servicios',
                    'badge_hero' => 'Soluciones Rapidas',
                    'badge_hero_sub' => 'Para tu negocio',
                    'titulo_nosotros' => 'Quienes Somos',
                    'subtitulo_nosotros' => 'Conoce nuestra historia y proposito',
                    'titulo_servicios' => 'Nuestros Servicios',
                    'subtitulo_servicios' => 'Soluciones a tu medida',
                    'texto_servicios' => 'Descubre como podemos ayudarte a alcanzar tus objetivos empresariales con nuestros servicios especializados.',
                    'titulo_contacto' => 'Listo para empezar?',
                    'texto_contacto' => 'Contactanos hoy mismo y descubre como podemos transformar tu negocio. Nuestro equipo esta listo para atenderte.',
                    'label_telefono' => 'Telefono',
                    'label_email' => 'Email',
                    'label_direccion' => 'Direccion',
                    'footer_derechos' => 'Todos los derechos reservados.',
                ],
            ],
            [
                'nombre_empresa' => 'Devbugging',
                'slug' => 'devbugging',
                'dominio' => 'devbugging.net',
                'tema' => 'minimal-light',
                'logo' => null,
                'imagen_principal' => 'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?auto=format&fit=crop&w=1400&q=80',
                'telefono' => 'Remote / international roles',
                'email' => 'hello@devbugging.net',
                'direccion' => 'Laravel, integrations, automation',
                'slogan' => 'Backend systems with practical engineering judgment.',
                'titulo_hero' => 'Laravel, integrations, automation, and production-grade backend systems.',
                'texto_hero' => 'I am a backend-first engineer with 8+ years of experience building, stabilizing, and improving production systems with PHP and Laravel. My strongest work lives in complex integrations, legacy refactors, asynchronous workflows, and operational automation.',
                'quienes_somos' => 'I work best on backend-heavy systems where stability, maintainability, and real business operations matter.',
                'caracteristicas' => [
                    ['titulo' => 'Complex integrations', 'descripcion' => 'Systems that depend on third-party APIs, marketplaces, banking services, Meta, WhatsApp, or internal tools.', 'icono' => 'M2.25 12.75l2.25 2.25 4.5-4.5m0 0 2.25 2.25 4.5-4.5m-6.75 2.25h13.5'],
                    ['titulo' => 'Legacy modernization', 'descripcion' => 'Refactoring brittle codebases without breaking the operation teams rely on every day.', 'icono' => 'M4.5 4.5h15v15h-15z M9 4.5v15 M15 4.5v15'],
                    ['titulo' => 'Async workflows', 'descripcion' => 'Queue orchestration, retries, backoff strategies, and idempotent processing for unstable or high-volume flows.', 'icono' => 'M12 6v6l4 2m-10 6.75h12a2.25 2.25 0 002.25-2.25v-9A2.25 2.25 0 0016.5 5.25h-9A2.25 2.25 0 005.25 7.5v9A2.25 2.25 0 007.5 18.75z'],
                    ['titulo' => 'Operational automation', 'descripcion' => 'Replacing manual work with reliable backend processes and AI-assisted decision support where it is genuinely useful.', 'icono' => 'M10.5 6h9m-9 6h9m-9 6h9M4.5 6h.008v.008H4.5V6zm0 6h.008v.008H4.5V12zm0 6h.008v.008H4.5V18z'],
                ],
                'servicios' => [
                    ['titulo' => 'WhatsApp + Meta + OpenAI workflow refactor', 'descripcion' => 'Stabilized a non-deterministic messaging and AI-assisted flow affected by duplicated processing, race conditions, and async orchestration issues.', 'icono' => 'M3.75 13.5l10.5-11.25L12 10.5h8.25L9.75 21.75 12 13.5H3.75z'],
                    ['titulo' => 'E-commerce automation platform', 'descripcion' => 'Improved an operations-heavy e-commerce platform with multiple integrations, degraded performance, and scattered business logic.', 'icono' => 'M3.75 3h16.5v4.5H3.75V3zm0 6.75h16.5v11.25H3.75V9.75zm3 3h4.5v4.5H6.75v-4.5z'],
                    ['titulo' => 'Banking and business-critical integrations', 'descripcion' => 'Worked on systems connected to banking or fintech-like processes where reliability, data consistency, and operational clarity were critical.', 'icono' => 'M12 3l7.5 4.5v4.75c0 5.052-3.438 9.756-7.5 10.75-4.062-.994-7.5-5.698-7.5-10.75V7.5L12 3z'],
                    ['titulo' => 'Multi-branch dashboard and internal tools', 'descripcion' => 'Built or evolved internal systems with multi-branch visibility, permissions, centralized data, and operational workflows.', 'icono' => 'M3.75 5.25h16.5M3.75 12h16.5M3.75 18.75h16.5'],
                ],
                'orden_secciones' => Site::getDefaultSectionOrderForForm(),
                'cta_config' => array_merge(Site::getDefaultCtaConfig(), [
                    'enabled' => true,
                    'label' => 'Read technical notes',
                    'url' => 'https://devbugging.net/notes',
                    'placement' => 'hero',
                    'style' => 'secondary',
                    'open_in_new_tab' => true,
                ]),
                'social_links' => array_merge(Site::getDefaultSocialLinks(), [
                    'linkedin' => 'https://linkedin.com/in/devbugging',
                    'x' => 'https://x.com/devbugging',
                    'github' => null,
                    'contact_url' => 'mailto:hello@devbugging.net',
                ]),
                'seo_config' => array_merge(Site::getDefaultSeoConfig(), [
                    'meta_title' => 'Devbugging | Senior Backend Engineer',
                    'meta_description' => 'Senior Backend / Laravel Engineer focused on integrations, automation, legacy modernization, and production-grade backend systems.',
                    'meta_keywords' => 'Laravel, PHP, backend engineer, integrations, async workflows, automation',
                ]),
                'tracking_config' => Site::getDefaultTrackingConfig(),
                'textos_ui' => [
                    'nav_inicio' => 'Home',
                    'nav_nosotros' => 'What I Solve',
                    'nav_servicios' => 'Selected Work',
                    'nav_contacto' => 'Contact',
                    'cta_hero' => 'View projects',
                    'cta_hero_secundario' => 'Contact me',
                    'badge_hero' => '8+ years in production',
                    'badge_hero_sub' => 'PHP and Laravel specialist',
                    'titulo_nosotros' => 'What I help teams fix and ship',
                    'subtitulo_nosotros' => 'Backend-heavy systems where stability and maintainability matter',
                    'titulo_servicios' => 'Selected work',
                    'subtitulo_servicios' => 'Systems I have helped build, stabilize, or improve',
                    'texto_servicios' => 'A few examples of the backend systems, integration flows, and operational tooling I have worked on.',
                    'titulo_contacto' => 'Let us talk if you are hiring or building something complex',
                    'texto_contacto' => 'Contact me for senior backend roles, Laravel architecture work, integration-heavy systems, automation initiatives, or product engineering collaborations.',
                    'label_telefono' => 'Availability',
                    'label_email' => 'Email',
                    'label_direccion' => 'Focus',
                    'footer_derechos' => 'All rights reserved.',
                ],
            ],
            [
                'nombre_empresa' => 'Poemas, Historia y Palabras',
                'slug' => 'poemas-historia-y-palabras',
                'dominio' => 'poemashistoriaypalabras.com',
                'tema' => 'warm-brown',
                'logo' => null,
                'imagen_principal' => 'https://images.unsplash.com/photo-1507842217343-583bb7270b66?auto=format&fit=crop&w=1400&q=80',
                'telefono' => 'Articulos, talleres y comunidad',
                'email' => 'hola@poemashistoriaypalabras.com',
                'direccion' => 'Proyecto editorial en linea',
                'slogan' => 'Lecturas que unen memoria, poesia y lenguaje.',
                'titulo_hero' => 'Un espacio para leer la historia, la poesia y el poder de las palabras con calma.',
                'texto_hero' => 'Poemas, Historia y Palabras es una plataforma editorial para publicar ensayos, comentarios de lectura, exploraciones historicas y piezas breves que conectan memoria cultural, literatura y sensibilidad contemporanea.',
                'quienes_somos' => 'Este proyecto esta pensado para lectoras y lectores que disfrutan descubrir autores, contextos historicos, relaciones entre textos y nuevas formas de conversar con la palabra escrita.',
                'caracteristicas' => [
                    ['titulo' => 'Poesia comentada', 'descripcion' => 'Lecturas cercanas de poemas, imagenes, simbolos y voces que siguen dialogando con el presente.', 'icono' => 'M4.5 5.25h15M4.5 9.75h15M4.5 14.25h9'],
                    ['titulo' => 'Historia narrada', 'descripcion' => 'Contextos historicos explicados con claridad para entender mejor obras, movimientos y autores.', 'icono' => 'M12 6v6l4 2m-9.75 4.5h15a2.25 2.25 0 002.25-2.25v-9A2.25 2.25 0 0019.5 6.75h-15A2.25 2.25 0 002.25 9v9A2.25 2.25 0 004.5 20.25z'],
                    ['titulo' => 'Palabras con contexto', 'descripcion' => 'Ensayos y notas que exploran etimologias, lenguaje, estilo y memoria cultural.', 'icono' => 'M7.5 3.75h9A2.25 2.25 0 0118.75 6v12A2.25 2.25 0 0116.5 20.25h-9A2.25 2.25 0 015.25 18V6A2.25 2.25 0 017.5 3.75z'],
                ],
                'servicios' => [
                    ['titulo' => 'Lecturas guiadas', 'descripcion' => 'Recorridos editoriales para acercarse a un autor, un tema o un periodo historico desde textos seleccionados.', 'icono' => 'M12 6.75a.75.75 0 01.75.75v8.69l2.72-1.36a.75.75 0 01.67 1.34l-3.75 1.875a.75.75 0 01-.67 0L7.96 16.17a.75.75 0 11.67-1.34l2.62 1.31V7.5a.75.75 0 01.75-.75z'],
                    ['titulo' => 'Ensayos y articulos', 'descripcion' => 'Textos originales sobre poesia, historia cultural, lenguaje y lectura contemporanea.', 'icono' => 'M4.5 6.75h15m-15 4.5h15m-15 4.5h9'],
                    ['titulo' => 'Archivo de referencias', 'descripcion' => 'Una base editorial para reunir autores, obras, epocas y conexiones utiles para futuras lecturas.', 'icono' => 'M3.75 7.5h16.5M6 4.5h12A1.5 1.5 0 0119.5 6v12A1.5 1.5 0 0118 19.5H6A1.5 1.5 0 014.5 18V6A1.5 1.5 0 016 4.5z'],
                    ['titulo' => 'Talleres y colaboraciones', 'descripcion' => 'Espacio para actividades, clubs de lectura, colaboraciones editoriales y propuestas culturales.', 'icono' => 'M18 18.75V16.5a3 3 0 00-3-3h-6a3 3 0 00-3 3v2.25M12 12a3.75 3.75 0 100-7.5 3.75 3.75 0 000 7.5z'],
                ],
                'orden_secciones' => Site::getDefaultSectionOrderForForm(),
                'cta_config' => array_merge(Site::getDefaultCtaConfig(), [
                    'enabled' => true,
                    'label' => 'Suscribirme',
                    'url' => 'mailto:hola@poemashistoriaypalabras.com',
                    'placement' => 'contacto',
                    'style' => 'primary',
                ]),
                'social_links' => array_merge(Site::getDefaultSocialLinks(), [
                    'instagram' => 'https://instagram.com/poemashistoriaypalabras',
                    'facebook' => 'https://facebook.com/poemashistoriaypalabras',
                    'youtube' => 'https://youtube.com/@poemashistoriaypalabras',
                    'contact_url' => 'mailto:hola@poemashistoriaypalabras.com',
                ]),
                'seo_config' => array_merge(Site::getDefaultSeoConfig(), [
                    'meta_title' => 'Poemas, Historia y Palabras',
                    'meta_description' => 'Proyecto editorial sobre poesia, historia cultural y lenguaje.',
                    'meta_keywords' => 'poesia, historia, lenguaje, ensayos, literatura',
                ]),
                'tracking_config' => Site::getDefaultTrackingConfig(),
                'textos_ui' => [
                    'nav_inicio' => 'Inicio',
                    'nav_nosotros' => 'Enfoque',
                    'nav_servicios' => 'Contenido',
                    'nav_contacto' => 'Contacto',
                    'cta_hero' => 'Explorar contenido',
                    'cta_hero_secundario' => 'Escribeme',
                    'badge_hero' => 'Historia, poesia y lenguaje',
                    'badge_hero_sub' => 'Un proyecto editorial vivo',
                    'titulo_nosotros' => 'Lo que encontraras aqui',
                    'subtitulo_nosotros' => 'Lectura, memoria cultural y conversaciones con los textos',
                    'titulo_servicios' => 'Formatos del proyecto',
                    'subtitulo_servicios' => 'Ensayos, lecturas guiadas y comunidad alrededor de la palabra',
                    'texto_servicios' => 'La misma plantilla se adapta aqui para presentar un proyecto editorial con una voz mas cultural y reflexiva.',
                    'titulo_contacto' => 'Hablemos si quieres colaborar, proponer un taller o compartir lecturas',
                    'texto_contacto' => 'Si quieres seguir el proyecto, colaborar en una publicacion o conversar sobre literatura, historia y lenguaje, puedes escribir directamente.',
                    'label_telefono' => 'Formato',
                    'label_email' => 'Correo',
                    'label_direccion' => 'Proyecto',
                    'footer_derechos' => 'Todos los derechos reservados.',
                ],
            ],
        ];
    }
}
